# Generated by Django 3.2.4 on 2021-06-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nom',
            new_name='name',
        ),
    ]
